import { z } from 'zod'

export const siteInputSchema = z.object({
  id: z.string().optional(),
  code: z.string().min(1, 'กรุณากรอกรหัสสาขา/คลัง').max(20),
  stCode: z.string().optional().nullable(),
  name: z.string().min(1, 'กรุณากรอกชื่อสาขา/คลัง').max(100),
  nameEn: z.string().optional().nullable(),
  nickname: z.string().optional(),
  legalName: z.string().optional().nullable(),
  type: z.enum(['BRANCH', 'DC']).default('BRANCH'),
  province: z.string().optional().default('กรุงเทพมหานคร'),
  district: z.string().optional().nullable(),
  subdistrict: z.string().optional().nullable(),
  postalCode: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  googleMapsUrl: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  storeManagerName: z.string().optional().nullable(),
  storeManagerPhone: z.string().optional().nullable(),
  storeEmail: z.string().email('รูปแบบอีเมลไม่ถูกต้อง').optional().or(z.literal('')).nullable(),
  groupEmail: z.string().optional().nullable(),
  openingHours: z.string().optional().nullable(),
  rcvOpeningHours: z.string().optional().nullable(),
  storeGroup: z.string().optional().nullable(),
  rom: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  districtManager: z.string().optional().nullable(),
  active: z.boolean().optional().default(true),
})

export type SiteInputType = z.infer<typeof siteInputSchema>

export function toSitePrismaData(parsed: SiteInputType) {
  const code = parsed.code.trim().toUpperCase()
  return {
    code,
    stCode: parsed.stCode || null,
    name: parsed.name.trim(),
    nameEn: parsed.nameEn || null,
    nickname: parsed.nickname?.trim() || code,
    legalName: parsed.legalName || null,
    type: parsed.type,
    province: parsed.province || 'กรุงเทพมหานคร',
    district: parsed.district || null,
    subdistrict: parsed.subdistrict || null,
    postalCode: parsed.postalCode || null,
    address: parsed.address || null,
    latitude: parsed.latitude ?? null,
    longitude: parsed.longitude ?? null,
    googleMapsUrl: parsed.googleMapsUrl || null,
    phone: parsed.phone || null,
    storeManagerName: parsed.storeManagerName || null,
    storeManagerPhone: parsed.storeManagerPhone || null,
    storeEmail: parsed.storeEmail || null,
    groupEmail: parsed.groupEmail || null,
    openingHours: parsed.openingHours || null,
    rcvOpeningHours: parsed.rcvOpeningHours || null,
    storeGroup: parsed.storeGroup || null,
    rom: parsed.rom || null,
    region: parsed.region || null,
    districtManager: parsed.districtManager || null,
    active: parsed.active ?? true,
  }
}
