export const ADMIN_SECTION_IDS = [
  'vendor',
  'fee',
  'branch',
  'zone',
  'sla',
  'role',
  'sku',
  'payout',
  'tradein',
  'dashboard',
  'general',
  'pending',
] as const

export const SECTION_ALIAS: Record<string, string> = {
  '1': 'vendor',
  '2': 'fee',
  '3': 'branch',
  '4': 'zone',
  '5': 'sla',
  '6': 'role',
  '7': 'sku',
  '8': 'payout',
  '9': 'tradein',
  '10': 'dashboard',
  '11': 'general',
  '12': 'pending',
  // Named and slug aliases
  'vendors': 'vendor',
  'Vendors': 'vendor',
  'feerates': 'fee',
  'FeeRates': 'fee',
  'fee-rates': 'fee',
  'fees': 'fee',
  'branches': 'branch',
  'Branches': 'branch',
  'routing': 'zone',
  'Routing': 'zone',
  'routes': 'zone',
  'SLA': 'sla',
  'permissions': 'role',
  'Permissions': 'role',
  'roles': 'role',
  'repairsku': 'sku',
  'RepairSKU': 'sku',
  'repair-sku': 'sku',
  'skus': 'sku',
  'payoutcycles': 'payout',
  'PayoutCycles': 'payout',
  'payout-cycles': 'payout',
  'promotions': 'tradein',
  'Promotions': 'tradein',
  'dashboardwidgets': 'dashboard',
  'DashboardWidgets': 'dashboard',
  'dashboard-widgets': 'dashboard',
  'generalsettings': 'general',
  'GeneralSettings': 'general',
  'general-settings': 'general',
  'pendingvendorqueue': 'pending',
  'PendingVendorQueue': 'pending',
  'pending-vendor-queue': 'pending',
  'pending-vendor': 'pending',
}

export const VALID_SECTIONS = new Set<string>([
  ...ADMIN_SECTION_IDS,
  ...Object.keys(SECTION_ALIAS),
])
